### ISSUE TITLE
MvcSitemapProvider v4

### ISSUE THREAD

**Issue by maartenba** [maartenba/MvcSiteMapProvider#119]
As it's been a while since ASP.NET MVC 4 is out and seeing that ASP.NET Web API dropped dependencies on System.Web, I'm kind of looking at evolving MvcSitemapProvider in that direction too...

vNext would:
- Drop all references to System.Web and ASP.NET's sitemap provider model
- Provide support for dependency injection
- Get split into separate NuGet packages (Core containing assemblies, Web containing views / helpers)
- No longer rely on the internal view engine

That's the technical side. What about features? I would love to hear what you are using today, what you would not want to miss, what's currently missing, anything!

**Comment by NightOwl888** [comment]
@maartenba 

I have recently created a [port of the BoboBrowse (Java) faceted search engine in .NET](https://github.com/NightOwl888/BoboBrowse.Net). It is now in beta, [available on NuGet](https://www.nuget.org/packages/BoboBrowse.Net/), all unit tests are passing, and could use some more testing to ensure it is stable.

Note that there is a port of [BoboBrowse 2.x on codeplex](https://bobo.codeplex.com/), but I couldn't get the owner of the repo to cooperate in order to include a NuGet package, so I had to host it myself. That version is also not compatible with the latest version of Lucene.Net (3.0.3), and not documented, but this one is. It is a port of BoboBrowse 3.1.0, which has several more features including a Geo Facet Search, Time Range Search, and Histogram Facet Search.

You can see it in action by running the [CarDemo](https://github.com/NightOwl888/BoboBrowse.Net/tree/master/src/CarDemo) solution from the repo. Its not a great demo (also a port from the Java version), but it does the job.

That project falls into the same sort of category as MvcSiteMapProvider, since faceted search could be used for site navigation. I would appreciate if you could write a short blog and/or a tweet about it to see if we can get some beta testers on board.

**Comment by maartenba** [comment]
Consider it done, scheduled two tweets for today. Does it support plugging the storage engine?

**Comment by NightOwl888** [comment]
No, it is strictly a query engine. There are no special tools to build a search index - you just use Lucene.Net to do that. 

The only thing to keep in mind is that the NumericField is not supported. BoboBrowse requires that numeric and date data be stored in the index as formatted strings. I created a [document](https://github.com/NightOwl888/BoboBrowse.Net/wiki/Understanding-Formatting) to explain this because it seems many people were attempting to use NumericField and it didn't work and the original documentation was not very clear on that point. I even built a small project in Java to test using the NumericField and it just crashes. Changing it to a formatted string padded with leading zeros works like a charm. I improved the error message to indicate that NumericField is not supported, since the original one didn't explain the problem.

It plugs into Lucene.Net by decorating an open IndexReader class with a BoboIndexReader. Generally, the BoboIndexReader was setup to be run as a singleton. If you add the [BoboBrowse.Net.Spring package](http://www.nuget.org/packages/BoboBrowse.Net.Spring/), you can use an [XML file to configure browse facet handlers](https://github.com/NightOwl888/BoboBrowse.Net/wiki/Spring.Net-XML-Configuration) for each index, but in a nutshell, facet handlers are configured when the BoboIndexReader is created. There are runtime facet handlers in version 3.1.0 to get around that limitation when the facets contain information that is calculated on the fly.

On an open BoboIndexReader, you can then call Browse, passing in a BrowseRequest which can contain a lot of configuration about how to organize the results, the main parts being a set of BrowseSelections and a Lucene.Net Query.

There is a lot of code and most of it deals with sorting, grouping, and manipulating data types. In fact, there is about double the code there is in MvcSiteMapProvider. I have a sneaky suspicion that this entire library could be replaced by a couple of hundred lines of LINQ and proper use of Generics, but it is difficult to figure out how to separate the facet business logic from the sorting and grouping code, since both of them are using arrays and bit shifting. Working out how to do that and have it work seamlessly with Lucene.Net's clunky API would be much more work than simply porting something that is already working, even if it does mean bringing along a lot of extra features that are difficult to understand, not well documented, and may not even work properly in .NET. Fortunately, I have managed to get all of the tests to pass, which raises my confidence that at least the main part of the business logic works in .NET.

**Comment by maartenba** [comment]
Very nice! Will see if I can have a go with it.

**Comment by NightOwl888** [comment]
@maartenba 

I am working on build scripts for 2 jQuery plugins, and one of them (the main one) has multiple packages. I want to deploy them with NuGet, Bower, and NPM. 

After reading the docs on Bower, it seems that they only support 1 module per Git repo and use the tags to keep track of versioning. So, I opted to go with using submodules for each package using [this approach](http://blog.stackfull.com/2013/05/publishing-bower-components/). This solved another problem - how to keep the minified and regular scripts in sync.

I am planning to use MyGet to run the build. NuGet is working great. Bower (supposedly) will work off of the tags so there is no need to do a push. NPM on the other hand requires a push, and this is where I am getting tripped up.

Is it possible to configure the script to push all of the packages from the Git submodules to the current feed rather than using a feed per submodule, allowing a single "push upstream" command for all of the NPM packages, the same way we do it for multiple NuGet packages? If so, would the following command do that?

```
cd submodule\directory && npm push --registry https://www.myget.org/F/your-feed-name/npm
```

I found [the documentation](http://browsenpm.org/help#managingownersofpackages) that shows that you can allow multiple users to push to NPM, but I am not sure if that is relevant here or if that is possible to do on a MyGet server without making passwords public.

**Comment by NightOwl888** [comment]
Never mind. I found the NPM pack command as specified in your [documentation](http://docs.myget.org/docs/reference/build-services-for-npm#Build_process_for_packagejson_files). It wasn't very clear that step was necessary for NPM. Once the pack is done, MyGet publishes to the feed just fine.

**Comment by NightOwl888** [comment]
On a side note, trying to update submodules on MyGet fails when using SSH. I switched to HTTPS and it works, but it is a bit awkward to work with the submodules locally because of the different authentication scheme.

**Comment by maartenba** [comment]
Yeah only HTTP(S) is supported. We were not keen on asking users to hand us their key files to be able to work on the build machine.

**Comment by NightOwl888** [comment]
I see. Still, it would be nice if there were a way to set it up as SSH for local use, but have MyGet switch to HTTPS through some sort of configuration (either using a file or through the control panel).

**Comment by NightOwl888** [comment]
@maartenba 

I am attempting to push my first NPM package from MyGet to NPM's official registry. However, it doesn't seem to be working.

When I attempt to push, it says "some additional configuration required". It mentions an API key, but nowhere in the NPM documentation does it say anything about that.

Then I follow the link to "Package Sources" and try to enter my login credentials on the edit form for the "Npmjs.org" source, but it won't let me save. It says that "the package source specified is invalid" even though I left the URL the default of http://registry.npmjs.org/ (which I double checked against the NPM documentation). The form validation doesn't let me continue.

This is supposed to allow you to push upstream the same way you can with NuGet, isn't it? The documentation is a bit vague on that point. It seems to be focused on pushing a package onto the feed, but it isn't clear how to

1. Install a package locally from the MyGet feed (to test it)
2. Push a package to the official Npmjs.org feed

which are the only tasks I am interested in.

If you want to take a look, the feed I am working with is here: https://www.myget.org/feed/Packages/jquery-facebox

**Comment by maartenba** [comment]
Added myself to the feed. Seems the NPM package source is missing a username/password.

**Comment by NightOwl888** [comment]
Right. And how can I add them if it is not possible to save the NPM package source form?

**Comment by maartenba** [comment]
Does it show an error message next to the username or pwd box on save? (ping me via email)

**Comment by NightOwl888** [comment]
No, it says "the package source specified is invalid" next to the NPM URL (even though I didn't change it from the default). I presume the validation code has not been updated to allow this URL: http://registry.npmjs.org/.

**Comment by maartenba** [comment]
Can you email me?

**Comment by nrodriguez2001** [comment]
After installi SiteMap v5 and deploy to IIS we are getting an error like below:

 Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

Source Error:


Line 4:  @using System.Web.UI.WebControls
Line 5:  @using Microsoft.AspNet.Identity
Line 6:  @using Microsoft.VisualStudio.Web.PageInspector.Runtime
Line 7:  <!DOCTYPE html>


Any ideas to solve this issue?

**Comment by nrodriguez2001** [comment]
I got this error

System.StackOverflowException was unhandled
Message: An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

running the MVC 5 version

**Comment by DilHem** [comment]
Hey All,
Its Urgent,

Can anyone provide me C language code for fuzzy logic speed controller. I'm doing this Using ENERGIA interface. 
I'm taking my inputs using a ultrasonic sensor and after fuzzy methods the outputs are taken by DC motors as their inputs and then after they are going to control the speed or the rotation speed of DC motor.

I'm thankful if anyone can provide the C language code for this.

Thank You
