### ISSUE TITLE
Strange issue when precompiling ASP.NET MVC app

### ISSUE THREAD

**Issue by brgrz** [maartenba/MvcSiteMapProvider#170]
I've tried using MvcSiteMap with a precompiled app (precompilation options as a part of the Publish process in Visual Studio 2012). Very strange behaviour occurs, the MvcSitemap renders menus without ULs. If I turn precompilation off, everything works fine. Also if I just run with Ctrl+F5.

I tried searching for this on the internets but found nothing with regards to this specific issue.

Somehow the precompilation renders the DisplayTemplates useless.

?

**Comment by ynauls** [comment]
Any new updates on this issue? i am running into this when building my application using AspNetCompiler Task (https://msdn.microsoft.com/en-us/library/ms164291(v=vs.120).aspx) .   The only solution is to NOT build the project using this task, however, due to project requirements, we must use this to build the application.
