### ISSUE TITLE
Documentation subclassing authorizeattribute 

### ISSUE THREAD

**Issue by Atrejoe** [maartenba/MvcSiteMapProvider#385]
The documentation on subclassing the authorizeattribute state that: 
>...your implementation of AuthorizeAttribute must set the filterContext.Result property to null if it succeeds and set it to a non-null value if it fails...

See:
https://github.com/maartenba/MvcSiteMapProvider/wiki/Security-Trimming#subclassing-authorizeattribute

However, when I look at the referred documentation:
http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/AuthorizeAttribute.cs

I do not see the filterContext.Result be set to null explicitly. It only set the filterContext.Result to a value when the authorization fails.

Probably the writer meant that filterContext.Result is normally originally null when calling passed to this method, and should not be set to a non-null value in case of successful authorization.

@maartenba Can you confirm this?

**Comment by maartenba** [comment]
It is indeed normally null.

**Comment by NightOwl888** [comment]
You are correct, you do not need to set filterContext.Result to null explicitly because that is its default value.

However, this only applies if you override `OnAuthorization`. In most cases, it makes more sense to override `AuthorizeCore`, in which case you can just rely on the default behavior of AuthorizeAttribute.

**Comment by Atrejoe** [comment]
Okay thanks, just to be clear.
