### ISSUE TITLE
Wildcard IncludeAssembliesForScan

### ISSUE THREAD

**Issue by pyromanci** [maartenba/MvcSiteMapProvider#393]
Is there a way to wildcard the IncludeAssembliesForScan setting? 

I have 3 other assemblies that start with the same string "WebsiteArea." and i have more i'm working on.  Instead of having to constantly remember to add the assemblies into the setting, it would be nice if i could do something like:
`<add key="MvcSiteMapProvider_IncludeAssembliesForScan" value="MainSite, WebsiteArea.*" />`

**Comment by NightOwl888** [comment]
Yes, you could use [`MvcSiteMapProvider_ExcludeAssembliesForScan`](https://github.com/maartenba/MvcSiteMapProvider/wiki/Configuring-MvcSiteMapProvider#mvcsitemapprovider_excludeassembliesforscan) rather than `MvcSiteMapProvider_IncludeAssembliesForScan` and then it will include all assemblies by default and you can filter them from there.

Do note that this is less efficient than using `MvcSiteMapProvider_IncludeAssembliesForScan` because there will be more to reflect over to find the attributes/custom classes.

**Comment by pyromanci** [comment]
So if I understand correctly. 

I drop the MvcSiteMapProvider_IncludeAssembliesForScan entry in the web.config and replace it with 
MvcSiteMapProvider_ExcludeAssembliesForScan. Correct?

If so that seems kind of backwards.

**Comment by NightOwl888** [comment]
Correct. Technically it is backwards, but that is what you are looking for. The original implementation scanned everything and had this filter to exclude libraries by name. But since then the `MvcSiteMapProvider_IncludeAssembliesForScan` setting was added is to include assemblies by name to make it more efficient (and intuitive).

**Comment by NightOwl888** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen it if that is not the case.
