### ISSUE TITLE
Allow programmatic creation of Mvc.sitemap in MVC5 app

### ISSUE THREAD

**Issue by alcibiades-ej** [maartenba/MvcSiteMapProvider#399]
Hello, everyone.

I may be retarded, but I cannot find a working sample of how to create a Mvc.sitemap programmatically--with C#.

My intention is to go to an Admin page in my application, and configure a Mvc.sitemap. The config data would be stored in a DB, of course, and would take effect immediately.

Thank you.

**Comment by NightOwl888** [comment]
Hi,

First of all, `MvcSiteMapProvider` is set up to pull data from sources and then it automatically manages the cache for you. You don't programmatically push data into a SiteMap because the SiteMap is cached (and read-only). It isn't designed to work without a cache (although some people do it). The design (which is based on Microsoft's design) is for a high proportion of reads and a low proportion of updates (i.e. There is 1 or 2 super users who goes in and edits it occasionally, and there are hundreds or thousands of requests to read it in between). If you have an application that has several users that each need to edit the sitemap and you expect the number of pages to grow exponentially, then you might be better off rolling your own custom solution (or you can fake it with ours, read on...).

But to answer your question, there are 2 ways to load data dynamically, and one way to "fake it". All of these methods can be used simultaneously, if necessary (although faking it just applies to a certain node and its descendants rather than the whole SiteMap but can be done multiple times).

## Loading Data Dynamically

In the first 2 cases, the data will end up in the cache. You can use the [`SiteMapCacheReleaseAttribute`](https://github.com/maartenba/MvcSiteMapProvider/wiki/Defining-sitemap-nodes-using-IDynamicNodeProvider#caching) on action methods that change data that will result in SiteMap updates, and it will automatically invalidate the cache and reload all of the SiteMap data on the next request. This of course works best if the size of your SiteMap is not too prohibitive (< 2500 nodes).

The 2 ways are:

1. Use a [Dynamic Node Provider](https://github.com/maartenba/MvcSiteMapProvider/wiki/Defining-sitemap-nodes-using-IDynamicNodeProvider)
2. Use a custom [ISiteMapNodeProvider](http://stackoverflow.com/questions/27772286/how-to-register-custom-sitemapnodeprovider-unity-di).

In both cases, it is possible to load either a flat set of data below a certain node, or to programmatically create a hierarchy of nodes.

Dynamic Node Provider requires you to make a definition node to declare each provider on (the definition node won't be in the SiteMap), and it is not possible to add the root node (typically the home page node) with a dynamic node provider.

ISiteMapNodeProvider allows you to load the entire SiteMap including the root node, but currently requires you to use an external DI container to inject it.

See these pages for more info:

http://stackoverflow.com/questions/19838084/how-to-implement-custom-sitemapnodeprovider
http://stackoverflow.com/questions/26487374/with-mvcsitemapprovider-is-it-possible-to-programattically-register-lots-of-page

## Faking It

You can also use `preservedRouteParameters` on certain route values to dynamically match a specific node to several pages, and then change the node's title programmatically or using the [SiteMapTitleAttribute](https://github.com/maartenba/MvcSiteMapProvider/wiki/Using-Action-Filter-Attributes#sitemaptitle). Usually, this will also require some [node visibility configuration](https://github.com/maartenba/MvcSiteMapProvider/wiki/Advanced-Node-Visibility-with-ISiteMapNodeVisibilityProvider) to hide nodes that you don't want in the SiteMap.

This is the recommended approach for pages that do CRUD applications (data maintenance) because it circumvents the cache altogether and will scale to handle dynamically changing data.

It does have its drawbacks, though:

1. It typically requires the URL to contain all of the information for its ancestor nodes (although you can get around this by using external DI to customize the code)
2. You are not allowed to use the same route value with 2 different meanings within the same ancestry (i.e. "id" cannot be used for both "customer" and "customer address", you need a "customerId" and "addressId" in your route values)
3. Both of the above limitations generally mean you need a custom route or a custom RouteBase subclass.
4. To update the title, the string value of the title must be available within the Action method.
5. It typically requires some configuration to hide some nodes that are required for the scenario that are not required on the UI.
6. The breadcrumb will work, but you are generally expected to build your own menu navigation to get to the individual pages (which works well if you are displaying a grid or list of database records on the page).
7. There is currently no way to add the nodes that are configured this way to the `/sitemap.xml` endpoint.

There is a post that goes into detail about this approach (along with several demos) here: http://www.shiningtreasures.com/post/2013/09/02/how-to-make-mvcsitemapprovider-remember-a-user-position#forcing-a-match

**Comment by alcibiades-ej** [comment]
NightOwl888: I am very grateful to you for the time and effort expended to answer my post. My app's menu system will rarely change. The information that you've provided is extremely helpful. Again, thank you!

**Comment by NightOwl888** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen if that is not the case.
