### ISSUE TITLE
MvcBuildViews - HtmlHelper extension errors

### ISSUE THREAD

**Issue by agentKnipe** [maartenba/MvcSiteMapProvider#402]
When attempting to use MvcBuildViews to compile views during a build, the SiteMapProvider views error out.  This does not seem to be an error when MvcBuildViews is disabled.

"Error	8	'System.Web.WebPages.Html.HtmlHelper' does not contain a definition for 'DisplayFor' and no extension method 'DisplayFor' accepting a first argument of type 'System.Web.WebPages.Html.HtmlHelper' could be found (are you missing a using directive or an assembly reference?)	c:\inetpub\wwwroot\XXXXX\packages\MvcSiteMapProvider.Web.4.6.1\content\Views\Shared\DisplayTemplates\MenuHelperModel.cshtml	9	18	Miscellaneous Files
"
"Error	5	The name 'model' does not exist in the current context	c:\inetpub\wwwroot\XXXXX\packages\MvcSiteMapProvider.Web.4.6.1\content\Views\Shared\DisplayTemplates\SiteMapHelperModel.cshtml	1	2	Miscellaneous Files
"

**Comment by NightOwl888** [comment]
All of the stock `MvcSiteMapProvider` helpers are templated. That is, they have dependencies in the `/Views/Shared/DisplayTemplates/` directory. I suspect the problem is that you are not including these dependencies for the views to build.

If it turns out that there is no way to do that, you could build your own HTML helpers that just return an `HtmlString` data type, that are based on the built in helpers. We made them templated so the HTML is easy to change, but there is no reason why you couldn't make your own HTML helpers that are custom coded to output the HTML you need rather than using templates.

**Comment by agentKnipe** [comment]
Thanks for getting back to me, do you know where I would add these dependencies, again, they we working fine without the [MVCBuildViews enabled](http://blogs.msdn.com/b/jimlamb/archive/2010/04/20/turn-on-compile-time-view-checking-for-asp-net-mvc-projects-in-tfs-build-2010.aspx).

Is there a flag or something that I need to set in the web.config?

**Comment by NightOwl888** [comment]
As DisplayTemplates/EditorTemplates and MvcBuildViews are both native features of MVC, I have no idea how (or if) they are designed to work together. This is a question better suited for [StackOverflow](http://stackoverflow.com/).

You might try copying the templates into the `c:\inetpub\wwwroot\XXXXX\packages\MvcSiteMapProvider.Web.4.6.1\content\Views\Shared\DisplayTemplates\` folder in your build script/MSBuild file, as that is apparently where your build is looking for them according to the error message.

**Comment by agentKnipe** [comment]
Thanks, I will go have a look at StackOverflow and see what I can find.  I just had a look at the packages folder, and the default templates are there, and we are using them as is.
