### ISSUE TITLE
WebActivatorEx is still required

### ISSUE THREAD

**Issue by waynebrantley** [maartenba/MvcSiteMapProvider#415]
MvcSiteMapProvider.Mvc5.DI.Autofac has a dependency on MvcSiteMapProvider.MVC5 (instead of MvcSiteMapProvider.MVC5.Core) making the WebActivatorEx now required.

I do not use that WebActivatorEx and launch items from startup.cs, etc.

Can this be reworked?

**Comment by NightOwl888** [comment]
The current plan is to phase out the "external DI" vs "internal DI" and to make a unified fluent configuration API that does everything (complete with extension methods for OWIN startup), so at this stage I would not be inclined to do such a thing. Not to mention, the `MvcSiteMapProvider.MVC5.DI.Autofac` package depends on `WebActivatorEx` directly so it wouldn't be possible to do anyway.

You can still get the files into your project without the WebActivator dependency with a little effort. There is really little point in using the NuGet package, as NuGet doesn't correctly handle configuration files anyway (one of many arguments for phasing out these packages).

1. Install `MvcSiteMapProvider.MVC5.Core` into your project.
2. Install `MvcSiteMapProvider.Web` into your project.
3. In the main `web.config` file, change the `MvcSiteMapProvider_UseExternalDIContainer` setting to `true` (you may delete any other `MvcSiteMapProvider_` settings as they are not required with external DI).
4. Create a new (throw away) MVC5 project targeting the same .NET framework version as your original.
5. Install `MvcSiteMapProvider.MVC5.DI.Autofac` into the new project (if using VS2015, select the `Highest Minor` dependency behavior)
6. If not using VS2015, execute the command `Update-Package MvcSiteMapProvider.MVC5.DI.Autofac.Modules -IgnoreDependencies`.
7. Copy the following files into your real project (the ones denoted with `*` are all you need if you already have a composition root in your project).
  1. `/DI/CommonConventions.cs` *
  2. `/DI/Autofac/Modules/MvcModule.cs` (optional) *
  3. `/DI/Autofac/Modules/MvcSiteMapProviderModule.cs` *
  4. `/DI/Autofac/ReadMe.txt` (optional) *
  5. `/DI/Autofac/DependencyInjectionContainer.cs`
  6. `/DI/IDpenendencyInjectionContainer.cs`
  7. `/DI/InjectableControllerFactory.cs`
  8. `/DI/InjectableDependencyResolver.cs`
  9. `/App_Start/CompositionRoot.cs`
  10. `/App_Start/DIConfig.cs`
  11. `/App_Start/MvcSiteMapProviderConfig.cs`
8. Remove the line `[assembly: WebActivatorEx.PostApplicationStartMethod(typeof(DIConfig), "Register")]` from the `DIConfig.cs` file.
9. Add a method call in your application startup to the static `DIConfig.Register()` method.
10. In the `MvcSiteMapProviderModule.cs` file, update the project name in the `includeAssembliesForScan` array to match your live project assembly name.

**Comment by waynebrantley** [comment]
I think the OWIN and a single config is a great feature.  It took me longer to sort out all the issues with the code you added than to just copy and paste 'how to implement with autofac' from a doc.   

To be clear, are you saying I can just remove the Autofac package - there is nothing in there that I need?

**Comment by NightOwl888** [comment]
What I am saying is that the only purpose of the `MvcSiteMapProvider.MVC5.DI.Autofac` and `MvcSiteMapProvider.MVC5.DI.Autofac.Modules` NuGet packages are to deliver a DI configuration into your project with the logical defaults. They only deliver code files, no DLLs. The reason for WebActivator is to make it "just work" without having to add any additional code.

Once the code is in your project, NuGet is just in the way because you are likely to customize the configuration and NuGet isn't smart enough to do a source code merge with any changes anyway. Furthermore, upon each minor version release it will prompt you whether to overwrite your configuration (usually the answer is no if you customized it). It would be safer if you just copy the files and not have to worry about NuGet doing this when updating to the latest version of `MvcStieMapProvider`.

I am being careful to ensure that no changes are introduced that break existing DI configurations and the [releases page](https://github.com/maartenba/MvcSiteMapProvider/releases) has instructions for getting the latest updates for these files when upgrading `MvcSiteMapProvider`.

The fluent API has been on the drawing board for a very long time. Once it is added it will provide the logical defaults using a builder rather than a DI container. You will still be able to inject dependencies (either by newing them up or with a DI container), but there won't be any container-specific support in the project. The approach taken here is a variation of the [conforming container](http://blog.ploeh.dk/2014/05/19/conforming-container/) anti-pattern, which has many of the same drawbacks. The main drawback is that currently for DI to work you have to provide an entire configuration. My thought for the API is to combine the techniques of [DI friendly library](http://blog.ploeh.dk/2014/05/19/di-friendly-library/) and [DI friendly framework](http://blog.ploeh.dk/2014/05/19/di-friendly-framework/) so you can get a default configuration and then override only the part that you want to customize.

But for now you still need to wire up the entire configuration with external DI if you wish to customize it. You can use the instructions I provided above to get that entire configuration. Or if you already have a composition root in your project, you can just copy the files with asterisks and follow the instructions in the readme to integrate the modules into your existing DI configuration.

**Comment by waynebrantley** [comment]
I did not understand that is what those Autofac packages were for!  If I had known that, I would not have installed and it would have saved me some headache!   So, I am all for you removing them and their code and people just following a 'how to hookup with autofac'.


I removed the autofac* files.   I now have MvcSiteMapProvider.Mvc5, MvcSiteMapProvider.Mvc5.Core and MvcSiteMapProvider.Web packages installed.  However, MvcSiteMapProvider.Mvc5 package still has the WebActivatorEx dependency.

Along the same lines as the above code, I inspected the packages and have now removed everything but MvcSiteMapProvider.Mvc5.Core and it all looks great.   That is what I really want (assuming this is correct?)

BTW, thanks for all your work on upgrading this project from version 3 to 4.  You have spent a ton of time and done a great job!

**Comment by mwpowellhtx** [comment]
So, does being closed won't fix mean that the configuration is now fluent? Definitely I concur nuget delivering raw code into my projects is less than desirable. I don't know why anyone would want that anyway. Thanks for the library and for the suggestions.

**Comment by mwpowellhtx** [comment]
Also, to clarify, it seems with the latest integration files/examples, half of the steps are now obsolete? Would you confirm? Thank you...

**Comment by NightOwl888** [comment]
This issue is closed because it is specifically about removing WebActivator from the DI package, which isn't something that can be changed without breaking the "just work" part of the package.

The Fluent API is still on the drawing board, but at the present I have other responsibilities that are preventing me from completing it.

The above instructions were also specifically tailored to remove the dependency on `WebActivatorEx`. The only purpose for WebActivator is to make the configuration startup automatically, rather than having to add a line of code to your `Application_Start` section to make it run. Either way will suffice, but if you are keeping WebActivator, you could reduce the steps to:

1. Install  MvcSiteMapProvider.MVC5  into your project.
2. In the main  web.config  file, change the  MvcSiteMapProvider_UseExternalDIContainer  setting to  true  (you may delete any other  MvcSiteMapProvider_  settings as they are not required with external DI).
3. Create a new (throw away) MVC5 project targeting the same .NET framework version as your original.
4. Install  MvcSiteMapProvider.MVC5.DI.Autofac  into the new project (if using VS2015, select the  Highest Minor  dependency behavior)
5. If not using VS2015, execute the command  `Update-Package MvcSiteMapProvider.MVC5.DI.Autofac.Modules -IgnoreDependencies`.
6. Copy the following files into your real project (the ones denoted with  *  are all you need if you already have a composition root in your project). 
  1. `/DI/CommonConventions.cs` *
  2. `/DI/Autofac/Modules/MvcModule.cs` (optional) *
  3. `/DI/Autofac/Modules/MvcSiteMapProviderModule.cs` *
  4. `/DI/Autofac/ReadMe.txt` (optional) *
  5. `/DI/Autofac/DependencyInjectionContainer.cs`
  6. `/DI/IDpenendencyInjectionContainer.cs`
  7. `/DI/InjectableControllerFactory.cs`
  8. `/DI/InjectableDependencyResolver.cs`
  9. `/App_Start/CompositionRoot.cs`
  10. `/App_Start/DIConfig.cs`
  11. `/App_Start/MvcSiteMapProviderConfig.cs`
7. In the  MvcSiteMapProviderModule.cs  file, update the project name in the  includeAssembliesForScan  array to match your live project assembly name.

**Comment by mwpowellhtx** [comment]
Thanks for the feedback.

If it's buying my anything, or a package depends on it, even for the moment, I'll keep it around. If not, then would like to drop it, probably. At least that's my thinking on the subject.

Thank you...
