### ISSUE TITLE
Support multiple top level nodes

### ISSUE THREAD

**Issue by mwpowellhtx** [maartenba/MvcSiteMapProvider#432]
In the default Xsd there is support for just one top-level [SiteMapNodeModel](http://github.com/maartenba/MvcSiteMapProvider/blob/master/src/MvcSiteMapProvider/MvcSiteMapProvider/Web/Html/Models/SiteMapNodeModel.cs). I'd like to extend that to support multiple top-level nodes. There would still be the need for children, but want to have more than one top level.

At present, this seems to be as baked into the Xsd as it is in the Assembly bits, which makes it difficult to just tweak the Xsd to taste.

Thank you...

**Comment by NightOwl888** [comment]
The XSD is installed into the root of your project by the `MvcSiteMapProvider.Web` package, so you can edit it. However, it is primarily there to support VS intellisense as editing the file would put it out of sync with the [`XmlSiteMapNodeProvider`](https://github.com/maartenba/MvcSiteMapProvider/blob/master/src/MvcSiteMapProvider/MvcSiteMapProvider/Builder/XmlSiteMapNodeProvider.cs), which actually loads the file.

There is also an inherit limitation of a `SiteMap` object (which the XML ultimately populates) - it can only have one root node. But since a web site can only have a single home page, this is the most logical behavior.

It might help to know what you are attempting to achieve.

**Comment by mwpowellhtx** [comment]
Just my way of wrapping my way around web versus desktop, WinForms, WPF, etc.

A little off topic; is there a way to support conditional, or even forms-based, nodes? For instance, the Login/Logoff condition, support for anti-forgery tokens, etc.

**Comment by NightOwl888** [comment]
You can [make a node "conditional" in several ways](http://stackoverflow.com/questions/26541338/load-an-xml-sitemap-into-mvcsitemapprovider-based-on-user-role), generally by choosing whether or not to display it.

You can make a node forms-based by changing the display templates to render a form based on whether a [custom attribute](https://github.com/maartenba/MvcSiteMapProvider/wiki/Using-Custom-Attributes-on-a-Node) is present. However, in general it doesn't make much sense to do this because a form POST does not normally represent a navigation point in the site hierarchy, those are typically GET requests.

**Comment by NightOwl888** [comment]
Do note that you can [hide the root node](http://stackoverflow.com/questions/28726214/how-to-hide-root-level-when-using-mvcsitemapprovider) to make a `SiteMapPath` that doesn't display home as the default location. In the menu control, there is an option to set `showStartingNode` to `false`.

**Comment by mwpowellhtx** [comment]
Okay, so that's like the fourth or fifth parameter in Menu. What do you do for a ``startingNode`` or ``startingNodeInChildLevel``? ``null`` and ``null``? ``Model.First()``?

```
@Html.MvcSiteMap().Menu("BootstrapMenuHelperModel")
```

**Comment by mwpowellhtx** [comment]
Ah, never mind. I see. It's one version of ``Menu()`` among many others. Works beautifully, thank you.
